import random

import random

ALL_EXAMPLES = [
        "I don’t chase green candles. I ride {groupName}.",
    "It’s not luck. It’s {groupName}.",
    "Found my alpha. It’s called {groupName}.",
    "Logged in, saw {groupName}, smiled.",
    "Some coins are just different. {groupName} hits.",
    "No meme hits harder than {groupName}.",
    "Every raid powers up {groupName}.",
    "Wake. Raid. {groupName}. Repeat.",
    "Felt cute, might ape more {groupName} later.",
    "Manifesting gains through {groupName}.",
    "Can’t talk right now, I’m raiding for {groupName}.",
    "Coffee and {groupName} to start the day.",
    "Living rent free in my head: {groupName}.",
    "That chart? Screaming {groupName}.",
    "If you know, you're stacking {groupName}.",
    "I stay bullish on {groupName} no matter what.",
    "Call it what you want, I call it {groupName} season.",
    "Saw the meme, bought the coin: {groupName}.",
    "Only vibes and {groupName} in this wallet.",
    "Nobody raids like the {groupName} crew.",
    "This energy? Straight from {groupName}.",
    "The coin that makes you tweet louder: {groupName}.",
    "Another day, another {groupName} win.",
    "I blinked and {groupName} was trending again.",
    "My conviction? Unshakable. {groupName}.",
    "Backed by memes, fueled by madness. {groupName}.",
    "I’m not here to argue. I’m here for {groupName}.",
    "Feels good being early to {groupName}.",
    "You’ll remember this moment: {groupName}.",
    "Bet you wish you clicked that chart. {groupName}.",
    "No fud zone. Only {groupName}.",
    "Vibes immaculate. Memes unmatched. {groupName}.",
    "It’s not a project, it’s a movement. {groupName}.",
    "Watching {groupName} cook in real-time. 🔥",
    "Degen-certified coin of the week: {groupName}.",
    "The only red I see is the {groupName} logo.",
    "Swear this thing’s got plot armor. {groupName}.",
    "This coin is giving main character energy: {groupName}.",
    "Imagine fading {groupName}. Couldn’t be me.",
    "Bag check? Yep, full of {groupName}.",
    "Raided once, stayed for the memes. {groupName}.",
    "Some coins pump. {groupName} moves.",
    "This ain’t no rerun. It’s {groupName} going parabolic again.",
    "Not financial advice, just obsessed with {groupName}.",
    "Name another coin doing it like {groupName}. I’ll wait.",
    "First bag I’m checking in a crash? {groupName}.",
    "The real pump? The friends we made in {groupName}.",
    "Tell me you’re bullish without saying it. Me: {groupName}.",
    "Every scroll ends with {groupName}.",
    "Nobody told me crypto could be this fun. Thanks, {groupName}.",
    "This isn’t even the final form. {groupName}.",
    "Wake up babe, new {groupName} tweet dropped.",
    "There are levels to this. {groupName} is top floor.",
    "Buying {groupName} feels like a cheat code.",
    "This raid? Personal. {groupName}.",
    "You can keep your L1s. I’ll keep my {groupName}.",
    "Just a degen with a dream… and {groupName}.",
    "Can’t hear the haters over this {groupName} pump.",
    "Ape responsibly. But definitely ape {groupName}.",
    "That’s not a chart. That’s a launchpad. {groupName}.",
    "Looking for alpha? Found it. {groupName}.",
    "This project speaks fluent meme. {groupName}.",
    "Don’t mind me, just stacking more {groupName}.",
    "The way this community moves? Elite. {groupName}.",
    "The only thing I'm holding tighter than my breath: {groupName}.",
    "There’s bullish… and then there’s {groupName}.",
    "Made it to the cool side of crypto. Thanks, {groupName}.",
    "My watchlist is 1 token long. {groupName}.",
    "Crypto got fun again. All because of {groupName}.",
    "Degen mode activated. Holding {groupName}.",
    "I’m not leaving. I’m not selling. {groupName}.",
    "All in on the coin with culture. {groupName}.",
    "The floor is lava, but my {groupName} is chillin'.",
    "Most coins follow trends. {groupName} sets them.",
    "Scroll. Scroll. Boom. It’s {groupName}.",
    "One tweet away from virality. {groupName}.",
    "Feels like the early days of greatness. {groupName}.",
    "I don’t need a utility. I need {groupName}.",
    "No cap. Just {groupName}.",
    "This isn’t hype. This is legacy. {groupName}.",
    "I speak fluent meme. That’s why I hold {groupName}.",
    "Altcoin of the year? Has to be {groupName}.",
    "This isn’t a trend. It’s a takeover. {groupName}.",
    "They said it was just a meme. {groupName} proved them wrong.",
    "I don’t trade emotions, I hold {groupName}.",
    "This one? Straight from the meme gods. {groupName}.",
    "Already visualizing my exit tweet. {groupName} to the top.",
    "A coin with lore? Yes please. {groupName}.",
    "This ain’t no fork. It’s {groupName} original flavor.",
    "Got bored. Bought more {groupName}.",
    "The vibes are way too real. {groupName}.",
    "Next cycle’s king? I already crowned it: {groupName}.",
    "Haters gonna hate. {groupName} gonna moon.",
    "TL filled with {groupName}? That’s how you know.",
    "This isn’t even the pump yet. Just wait. {groupName}.",
    "Early believers always eat. {groupName}.",
    "Buying {groupName} feels like breaking the fourth wall.",
    "There’s a reason {groupName} shows up in every thread.",
    "I came for the memes. I stayed for the {groupName}.",
    "Going to the moon with this one 🚀",
    "This project just hits different.",
    "Been here since day 1. Let's go!",
    "The vibes are immaculate.",
    "Holding till my bags explode.",
    "Zero doubts. Only conviction.",
    "Injecting this into my veins.",
    "Chart looks spicy 🔥",
    "OGs know what's up.",
    "Don't fade the real ones.",
    "Yo, that’s bullish! Let’s go {groupName} 🚀",
    "BEST COMMUNITY SO FAR",
    "I’m feeling goated with {groupName} ✌️🔥",
    "One of the top crypto influencers is backing {groupName} — we knew first!",
    "The only memecoin that actually stands for something: {groupName}",
    "Ready for the {groupName} movement?",
    "A new era of profits starts with {groupName}",
    "{groupName} is inevitable, don’t be late! ⏳",
    "Meme it. Raid it. Stack it. {groupName} 🔥",
    "A memecoin with real history? That’s {groupName}.",
    "Bulls love {groupName}. Bears love {groupName}. Everyone loves {groupName}.",
    "“I told you so” moment incoming! {groupName} 🚀",
    "Witness history in the making with {groupName}",
    "War ends, profits begin. {groupName} dominates 🌍",
    "The coin that brings the world together: {groupName}",
    "FOMO kicking in yet? Time to ape in! {groupName}",
    "{groupName} to the moon, fueled by real events 🚀",
    "Don’t just watch, be part of it — join {groupName}",
    "Not just a memecoin. A revolution. {groupName}",
    "History is being written. {groupName} is the pen. 🖊️",
    "From raids to moon landings — {groupName} is unstoppable!",
    "Tell your friends or they’ll regret it later — {groupName}",
    "It’s happening. The {groupName} army is HERE 🔥",
    "The next big thing in crypto? {groupName}. Believe it.",
    "Meme with us. Win with us. {groupName}.",
    "First meme coin that feels like a movement. {groupName}.",
    "Every bag I packed has {groupName} in it.",
    "This vibe? Unmatched. {groupName}.",
    "The timeline is talking. {groupName} is trending.",
    "Say less. I’m already in {groupName}.",
    "You’ll wish you aped in earlier. {groupName}.",
    "No presale, no BS. Just {groupName}.",
    "This coin has character. {groupName} to the moon.",
    "Real ones already stacking {groupName}.",
    "This ain’t no rug. It’s {groupName}.",
    "Only one way this ends — with {groupName} on top.",
    "I ride with {groupName} until the wheels fall off.",
    "Can’t stop, won’t stop. {groupName}.",
    "This heat? Straight from {groupName}.",
    "Firing on all cylinders. {groupName} is that coin.",
    "We don’t follow trends. We are the trend. {groupName}.",
    "Pure community energy. That’s {groupName}.",
    "It’s giving… generational wealth. {groupName}.",
    "DYOR? Already did. That’s why I’m with {groupName}.",
    "Crypto’s next breakout star: {groupName}.",
    "Catch me tweeting about {groupName} all week.",
    "The bags are packed. Destination: {groupName}.",
    "Every tweet is bullish when it’s about {groupName}.",
    "No roadmap needed. Just vibes. {groupName}.",
    "I blinked and {groupName} exploded.",
    "Adding more {groupName} to the portfolio. Obviously.",
    "This isn’t hype. It’s a movement. {groupName}.",
    "Can’t believe people are still sleeping on {groupName}.",
    "If you know, you know. {groupName}.",
    "Remember this tweet. {groupName}.",
    "Watch this space. {groupName} is just getting started.",
    "Momentum like this doesn’t lie. {groupName}.",
    "The coin of the culture. {groupName}.",
    "Call it what you want — I call it {groupName} season.",
    "The future of crypto memes? It’s {groupName}.",
    "Still early. Still building. Still {groupName}.",
    "This tweet brought to you by {groupName}.",
    "We don’t chase pumps. We are the pump. {groupName}.",
    "You feel that? That’s the {groupName} wave.",
    "All signs point to {groupName}.",
    "This isn’t financial advice, but… {groupName}.",
    "I see green. I see gains. I see {groupName}.",
    "Stack, post, repeat. {groupName}.",
    "The prophecy is unfolding. {groupName}.",
    "Every raid makes {groupName} stronger.",
    "It’s time. {groupName}.",
]

def get_random_examples(n=20):
    return random.sample(ALL_EXAMPLES, min(n, len(ALL_EXAMPLES)))
